name: Deploy via Cloudflare Tunnel SSH

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect Tailscale
        run: |
          sudo tailscale up --authkey ${{ secrets.TS_AUTHKEY }}
          
      - name: Debug
        run: |
          tailscale status
          ip a
          
      - name: SSH ke server
        run: |
          ssh -vvv root@100.82.102.19
